### ISSUE TITLE
JS test interface sent bad reply

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-env-selenium#32] opened 2016-03-31 13:03 UTC
Hello. More bearing of bad news.

I'm consistently seeing:

```
JS test interface sent bad reply: msg:t1
```

while trying to test scalajs-react against Firefox on Travis CI.

Here's one example: https://travis-ci.org/japgolly/scalajs-react/jobs/119793233
Plenty of others in the Travis build history.

**Comment by nicolasstucki** [comment] 2016-04-18 13:21
@japgolly I have not been able to reproduce this bug and the code has had several changes since you reported it. Can you still reproduce it using the latest release?

**Comment by japgolly** [comment] 2016-04-18 21:49
Good morning @nicolasstucki. I just tried again with 0.1.2, it's still occurring: https://travis-ci.org/japgolly/scalajs-react/jobs/124027651

Repo branch is here: https://github.com/japgolly/scalajs-react/tree/travis

**Comment by sjrd** [comment] 2018-05-27 22:41
As mentioned in https://github.com/scala-js/scala-js/issues/2378#issuecomment-392382217, this error message has been wiped out in Scala.js 0.6.20, so I'm going to close this issue. It's possible that the underlying issue still exist, but it would surface with different symptoms.

**Closed as completed by sjrd** 2018-05-27 22:41 UTC
Labels: bug
